.class public final Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;
.super Ljava/lang/Object;
.source "SubtitlesStream.java"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "Builder"
.end annotation


# instance fields
.field private autoGenerated:Ljava/lang/Boolean;

.field private content:Ljava/lang/String;

.field private deliveryMethod:Lorg/schabi/newpipe/extractor/stream/DeliveryMethod;

.field private id:Ljava/lang/String;

.field private isUrl:Z

.field private languageCode:Ljava/lang/String;

.field private manifestUrl:Ljava/lang/String;

.field private mediaFormat:Lorg/schabi/newpipe/extractor/MediaFormat;


# direct methods
.method public constructor <init>()V
    .locals 1

    .line 39
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 27
    sget-object v0, Lorg/schabi/newpipe/extractor/stream/DeliveryMethod;->PROGRESSIVE_HTTP:Lorg/schabi/newpipe/extractor/stream/DeliveryMethod;

    iput-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->deliveryMethod:Lorg/schabi/newpipe/extractor/stream/DeliveryMethod;

    return-void
.end method


# virtual methods
.method public build()Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;
    .locals 11

    .line 175
    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->content:Ljava/lang/String;

    if-eqz v0, :cond_5

    .line 180
    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->deliveryMethod:Lorg/schabi/newpipe/extractor/stream/DeliveryMethod;

    if-eqz v0, :cond_4

    .line 187
    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->languageCode:Ljava/lang/String;

    if-eqz v0, :cond_3

    .line 193
    iget-object v1, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->autoGenerated:Ljava/lang/Boolean;

    if-eqz v1, :cond_2

    .line 199
    iget-object v1, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->id:Ljava/lang/String;

    if-nez v1, :cond_1

    .line 200
    iget-object v1, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->mediaFormat:Lorg/schabi/newpipe/extractor/MediaFormat;

    if-eqz v1, :cond_0

    iget-object v1, v1, Lorg/schabi/newpipe/extractor/MediaFormat;->suffix:Ljava/lang/String;

    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    const-string v3, "."

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    goto :goto_0

    .line 201
    :cond_0
    const-string v1, ""

    :goto_0
    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->id:Ljava/lang/String;

    .line 204
    :cond_1
    new-instance v1, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;

    iget-object v2, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->id:Ljava/lang/String;

    iget-object v3, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->content:Ljava/lang/String;

    iget-boolean v4, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->isUrl:Z

    iget-object v5, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->mediaFormat:Lorg/schabi/newpipe/extractor/MediaFormat;

    iget-object v6, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->deliveryMethod:Lorg/schabi/newpipe/extractor/stream/DeliveryMethod;

    iget-object v7, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->languageCode:Ljava/lang/String;

    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->autoGenerated:Ljava/lang/Boolean;

    .line 205
    invoke-virtual {v0}, Ljava/lang/Boolean;->booleanValue()Z

    move-result v8

    iget-object v9, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->manifestUrl:Ljava/lang/String;

    const/4 v10, 0x0

    invoke-direct/range {v1 .. v10}, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;-><init>(Ljava/lang/String;Ljava/lang/String;ZLorg/schabi/newpipe/extractor/MediaFormat;Lorg/schabi/newpipe/extractor/stream/DeliveryMethod;Ljava/lang/String;ZLjava/lang/String;Lorg/schabi/newpipe/extractor/stream/SubtitlesStream-IA;)V

    return-object v1

    .line 194
    :cond_2
    new-instance v0, Ljava/lang/IllegalStateException;

    const-string v1, "The subtitles stream has been not set as an autogenerated subtitles stream or not. Please specify this information with setIsAutoGenerated."

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 188
    :cond_3
    new-instance v0, Ljava/lang/IllegalStateException;

    const-string v1, "The language code of the subtitles stream has been not set or is null. Make sure you specified an non null language code with setLanguageCode."

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 181
    :cond_4
    new-instance v0, Ljava/lang/IllegalStateException;

    const-string v1, "The delivery method of the subtitles stream has been set as null, which is not allowed. Pass a valid one instead withsetDeliveryMethod."

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0

    .line 176
    :cond_5
    new-instance v0, Ljava/lang/IllegalStateException;

    const-string v1, "No valid content was specified. Please specify a valid one with setContent."

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0
.end method

.method public setAutoGenerated(Z)Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;
    .locals 0

    .line 151
    invoke-static {p1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    move-result-object p1

    iput-object p1, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->autoGenerated:Ljava/lang/Boolean;

    return-object p0
.end method

.method public setContent(Ljava/lang/String;Z)Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;
    .locals 0

    .line 68
    iput-object p1, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->content:Ljava/lang/String;

    .line 69
    iput-boolean p2, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->isUrl:Z

    return-object p0
.end method

.method public setLanguageCode(Ljava/lang/String;)Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;
    .locals 0

    .line 139
    iput-object p1, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->languageCode:Ljava/lang/String;

    return-object p0
.end method

.method public setMediaFormat(Lorg/schabi/newpipe/extractor/MediaFormat;)Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;
    .locals 0

    .line 93
    iput-object p1, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;->mediaFormat:Lorg/schabi/newpipe/extractor/MediaFormat;

    return-object p0
.end method
