.class public final Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;
.super Lorg/schabi/newpipe/extractor/stream/Stream;
.source "SubtitlesStream.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$Builder;
    }
.end annotation


# instance fields
.field private final autoGenerated:Z

.field private final code:Ljava/lang/String;

.field private final format:Lorg/schabi/newpipe/extractor/MediaFormat;

.field private final locale:Ljava/util/Locale;


# direct methods
.method public static synthetic $r8$lambda$Q5w_qRBAlv2CUgW2zsrDJu3vMe0(Ljava/lang/String;)Lorg/schabi/newpipe/extractor/exceptions/ParsingException;
    .locals 3

    .line 236
    new-instance v0, Lorg/schabi/newpipe/extractor/exceptions/ParsingException;

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    const-string v2, "not a valid locale language code: "

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v1, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object p0

    invoke-direct {v0, p0}, Lorg/schabi/newpipe/extractor/exceptions/ParsingException;-><init>(Ljava/lang/String;)V

    return-object v0
.end method

.method private constructor <init>(Ljava/lang/String;Ljava/lang/String;ZLorg/schabi/newpipe/extractor/MediaFormat;Lorg/schabi/newpipe/extractor/stream/DeliveryMethod;Ljava/lang/String;ZLjava/lang/String;)V
    .locals 7

    move-object v0, p0

    move-object v1, p1

    move-object v2, p2

    move v3, p3

    move-object v4, p4

    move-object v5, p5

    move-object v6, p8

    .line 234
    invoke-direct/range {v0 .. v6}, Lorg/schabi/newpipe/extractor/stream/Stream;-><init>(Ljava/lang/String;Ljava/lang/String;ZLorg/schabi/newpipe/extractor/MediaFormat;Lorg/schabi/newpipe/extractor/stream/DeliveryMethod;Ljava/lang/String;)V

    .line 235
    invoke-static {p6}, Lorg/schabi/newpipe/extractor/utils/LocaleCompat;->forLanguageTag(Ljava/lang/String;)Lj$/util/Optional;

    move-result-object p1

    new-instance p2, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$$ExternalSyntheticLambda0;

    invoke-direct {p2, p6}, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream$$ExternalSyntheticLambda0;-><init>(Ljava/lang/String;)V

    invoke-virtual {p1, p2}, Lj$/util/Optional;->orElseThrow(Ljava/util/function/Supplier;)Ljava/lang/Object;

    move-result-object p1

    check-cast p1, Ljava/util/Locale;

    iput-object p1, v0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->locale:Ljava/util/Locale;

    .line 238
    iput-object p6, v0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->code:Ljava/lang/String;

    .line 239
    iput-object v4, v0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->format:Lorg/schabi/newpipe/extractor/MediaFormat;

    .line 240
    iput-boolean p7, v0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->autoGenerated:Z

    return-void
.end method

.method synthetic constructor <init>(Ljava/lang/String;Ljava/lang/String;ZLorg/schabi/newpipe/extractor/MediaFormat;Lorg/schabi/newpipe/extractor/stream/DeliveryMethod;Ljava/lang/String;ZLjava/lang/String;Lorg/schabi/newpipe/extractor/stream/SubtitlesStream-IA;)V
    .locals 0

    .line 0
    invoke-direct/range {p0 .. p8}, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;-><init>(Ljava/lang/String;Ljava/lang/String;ZLorg/schabi/newpipe/extractor/MediaFormat;Lorg/schabi/newpipe/extractor/stream/DeliveryMethod;Ljava/lang/String;ZLjava/lang/String;)V

    return-void
.end method


# virtual methods
.method public equalStats(Lorg/schabi/newpipe/extractor/stream/Stream;)Z
    .locals 2

    .line 269
    invoke-super {p0, p1}, Lorg/schabi/newpipe/extractor/stream/Stream;->equalStats(Lorg/schabi/newpipe/extractor/stream/Stream;)Z

    move-result v0

    if-eqz v0, :cond_0

    instance-of v0, p1, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;

    if-eqz v0, :cond_0

    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->code:Ljava/lang/String;

    check-cast p1, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;

    iget-object v1, p1, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->code:Ljava/lang/String;

    .line 271
    invoke-virtual {v0, v1}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z

    move-result v0

    if-eqz v0, :cond_0

    iget-boolean v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->autoGenerated:Z

    iget-boolean p1, p1, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->autoGenerated:Z

    if-ne v0, p1, :cond_0

    const/4 p1, 0x1

    return p1

    :cond_0
    const/4 p1, 0x0

    return p1
.end method

.method public getDisplayLanguageName()Ljava/lang/String;
    .locals 1

    .line 281
    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->locale:Ljava/util/Locale;

    invoke-virtual {v0, v0}, Ljava/util/Locale;->getDisplayName(Ljava/util/Locale;)Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public getItagItem()Lorg/schabi/newpipe/extractor/services/youtube/ItagItem;
    .locals 1

    .line 0
    const/4 v0, 0x0

    return-object v0
.end method

.method public getLanguageTag()Ljava/lang/String;
    .locals 1

    .line 290
    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->code:Ljava/lang/String;

    return-object v0
.end method

.method public getLocale()Ljava/util/Locale;
    .locals 1

    .line 299
    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->locale:Ljava/util/Locale;

    return-object v0
.end method

.method public isAutoGenerated()Z
    .locals 1

    .line 261
    iget-boolean v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->autoGenerated:Z

    return v0
.end method
